{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-macosx64-1.0.klib",
          "size": 10415,
          "sha512": "ba4462cb117390d2794981d52cd50edb3b7952903c196c9ecd112fdfb5f9cf3bb6624a2767d8a412572c9d3e21fd2a40fc8657a0132f5e3b8721eed9f3f6034f",
          "sha256": "6dd9fb1e2760814328cb7a98bee48c323917a72e98e513d4ab0fb3837da49cb0",
          "sha1": "988b05c09eeba6280965670fd226c5043cf2747a",
          "md5": "cc45103ae8b26d54390d71511e93eef2"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-macosx64-1.0-sources.jar",
          "url": "binary-tree-utilities-macosx64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities-macosx64-1.0-metadata.jar",
          "url": "binary-tree-utilities-macosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "6d401ac05ab98f359aeae2a68dda3eb1c6756d41afbd7d51f7c3705dfbe5f97ef9064c4d8500d3f8a19ed8734575fe284d4d23cf4251091e00cebec40136897b",
          "sha256": "2540207f443d9d851754d9ba16ab3d45db67e31682ddead0dece94a75e5c8afa",
          "sha1": "988a3b8c83ea4052bb22062e3b05b55072780a26",
          "md5": "ae7d35de99d5d8c8fd8875ab81751abf"
        }
      ]
    }
  ]
}
