{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-androidnativex64-1.0.klib",
          "size": 10433,
          "sha512": "69582143ea1222f7006c61eabcc1d13f7576496719d7798503b88cf39ccb7f6790c188875071683fad59ebe3a82f910114bdac15344f7364fa4aa0f58a5b0d5c",
          "sha256": "b4b5822f60e156c847b27b3773ac63fae8d6e5f035e8c32755794c10f8f37e7a",
          "sha1": "2a081ad2d8057e313805c877e288bd18582bbb96",
          "md5": "063fa1a371cd642a8b6d6ce0d2104a64"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-androidnativex64-1.0-sources.jar",
          "url": "binary-tree-utilities-androidnativex64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    }
  ]
}
