{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-androidnativex86-1.0.klib",
          "size": 10433,
          "sha512": "2be89c87ab91a673a57ca4c9dcaa08ad66d589d93e36f42f9bf88e805c7957659fb3ea7a0648c6a4fdf2d7b3c861dd738f0625e0418793d758b82c93b7b6008a",
          "sha256": "3501c4d5d9f1fa7f2558ecc6805f864fd85d9f404f5f1c0bd60a80725af69966",
          "sha1": "31e47ffe4be18948dbb59800fada02698cb86b37",
          "md5": "c779990210edded3f762883bcfa49831"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-androidnativex86-1.0-sources.jar",
          "url": "binary-tree-utilities-androidnativex86-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    }
  ]
}
