{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-androidnativearm64-1.0.klib",
          "size": 10450,
          "sha512": "c9465b67e5125a6b7e9e414f2184937be39a59f62e37cddf1da67d8a6f3e9858c2822db00d97e497430596727a1a5bebe5e3a73f17f8dbbe488f7b24529d3464",
          "sha256": "ccbb3440c29d79e148fff029701e35d447f4fe16e16beaafab89331e541d4980",
          "sha1": "211da7ba28d901bbc96c5504c8ba6d544a8a4d0c",
          "md5": "ee318de3c67544e165aaee5cf9a0c541"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-androidnativearm64-1.0-sources.jar",
          "url": "binary-tree-utilities-androidnativearm64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    }
  ]
}
