{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-macosarm64-1.0.klib",
          "size": 10431,
          "sha512": "a4c8bf247a1324aeadceab396875c676f6d014ea790ecdc5e8f20084fbb0abcb957f559972ea631c7ef75b67de383f6c619faff140bb23bb2ab4d34f05cb9f70",
          "sha256": "396832bf43cb8e32204078c2d854c991001ef59717a24369053cd4749bccf03a",
          "sha1": "69fb2e8276fa7aaee6512425471945cac3948466",
          "md5": "002491dc90deb78e07a487c24b9a4e59"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-macosarm64-1.0-sources.jar",
          "url": "binary-tree-utilities-macosarm64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities-macosarm64-1.0-metadata.jar",
          "url": "binary-tree-utilities-macosarm64-1.0-metadata.jar",
          "size": 261,
          "sha512": "ed3b49790c672107a08165d685a17f19a1d1d74524da6120a3196bb96f0bab22ac4b2e7ef02fe7ad5b299c3759d511a0cf9c893702193ec302fe11c476465df4",
          "sha256": "0d853319c5ef2e7c0ffe80f8416d1a646437732101f4d98b60fa8acf25b71ace",
          "sha1": "2661bb43e0e49e23f32789f2457c45cf46457c9c",
          "md5": "d52ce896884344c13dbc74d35a6bab15"
        }
      ]
    }
  ]
}
