{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-tvosx64-1.0.klib",
          "size": 10406,
          "sha512": "5dbaf57db837435f4cf56ff368e5ab6e8aa9a70deb972266b629cbf785fb74ec4c9c5878fa3a5ed8069999a8caac0ffcce15b69f154a12547bd06fe99d42e0c7",
          "sha256": "28a0e55c4042f2024dc57e17e708836c9d1093c693c03b0f342452c175c9e37f",
          "sha1": "0a59dbb65de447d6b5790cb8bb2439ce6f2c3ea3",
          "md5": "db87d4defacaf85e3200511b46d6f135"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-tvosx64-1.0-sources.jar",
          "url": "binary-tree-utilities-tvosx64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities-tvosx64-1.0-metadata.jar",
          "url": "binary-tree-utilities-tvosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "961fef0cd225e5f1606ce2f7702a0e02a70658883a0efde4624bf0ce1a2d11229c5249351a3bb35f10b722727fbbe73056a2c0747d1b8a7cbd8af398c8189cc5",
          "sha256": "f0a8062205d3a0e4b1ab2a4900f2373c25b0a00df0a9ef630a60ee55b98f04b8",
          "sha1": "a3e835733b1b6f9404d92ee7e13825646932998b",
          "md5": "2bdf11311359a8970c1d5bc4ab4b3277"
        }
      ]
    }
  ]
}
