{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-iosx64-1.0.klib",
          "size": 10397,
          "sha512": "5dcbb74bcfd164de3938e745eaca26be82cb528b5a41d8440b5fd2a7975fe1da37658ef324941862740db10acd4fed131c2e42b13f691357e7a706c3799b127d",
          "sha256": "de461d42b90ffdee223bbd505fe1ad6455db254a9e2bc24002fc4fb46fa2d925",
          "sha1": "991419430649dcbeda667a01cec5e1d53d4fb1d9",
          "md5": "3257fc0745e3146b763b398633ed44f5"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-iosx64-1.0-sources.jar",
          "url": "binary-tree-utilities-iosx64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities-iosx64-1.0-metadata.jar",
          "url": "binary-tree-utilities-iosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "a1f303897f1bbf97c53d1cae5c0a5e53753f074572f3fef5801bb545a6760a95b9d90c09c90f8423f52ce285ef09b1d8368333849c842aa1690dcfbd1e907a99",
          "sha256": "1af27a6f6461877a1e168bd4cb36585e2dd6071f424afe65d8780453b46558f5",
          "sha1": "6f4eb66a028babd7098d1ebf1501f7a7b0de8208",
          "md5": "5c27b68892bffe39cf856433b15a64a3"
        }
      ]
    }
  ]
}
