{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-watchosx64-1.0.klib",
          "size": 10432,
          "sha512": "5e32e2a17c4fe6d65d415902592c0e1e6de7e5dfe9f3b2f8516131df03639e201885adeeb376f33e376dca8968ea18f681be003298ebe58255693c085b74a061",
          "sha256": "a5ae334796b8e2d3abf601c1c6d9d7f82a717a5546fa56b0c0f5d1279cd45277",
          "sha1": "c8ac41eeed5d17ffb42eb3794dda6115b64735a0",
          "md5": "c8873f0ea9030b5e030edf1eaa853fc3"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-watchosx64-1.0-sources.jar",
          "url": "binary-tree-utilities-watchosx64-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities-watchosx64-1.0-metadata.jar",
          "url": "binary-tree-utilities-watchosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "a131411c5b2ebd5c585c67f4cb659c4c3879c4118e8ed6256537c7366b99f933501edaa2b113b18010cb09f96af1d85c23d32e8ee23201494692e75422c7ddf5",
          "sha256": "d16dae031885ddc28d61f14793766ab377c5391d225acb6be994aa76a138cd20",
          "sha1": "e81980a327f40d0cc74ba6585ce53441d36c8671",
          "md5": "5e729cb71720cb7330c22df370133fd6"
        }
      ]
    }
  ]
}
