{
  "formatVersion": "1.1",
  "component": {
    "url": "../../binary-tree-utilities/1.0/binary-tree-utilities-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "binary-tree-utilities",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-tree-utilities.klib",
          "url": "binary-tree-utilities-androidnativearm32-1.0.klib",
          "size": 10450,
          "sha512": "ea8ff603eb1980a7d932bcbf8c2f85654b1b8cef5f3c8be7cff8c3415dad25d8dddc6fdd7620529a956a611d4dd68b58d8198f02e2552ee9b4563b51d20e60bc",
          "sha256": "998a9f119c2c233958223958f20fba173d795ab53b349c333ec059598164a92e",
          "sha1": "a5a47a690bf6b3c690c06459d54985041b4a85c4",
          "md5": "04f41cc8ab10bc580950a330fc322711"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "binary-tree-utilities-androidnativearm32-1.0-sources.jar",
          "url": "binary-tree-utilities-androidnativearm32-1.0-sources.jar",
          "size": 2228,
          "sha512": "31b21012b274b599760271ed62d4f66eaf1e581af0ba21334eb0e9a78f7d806d47c8ba4707618853cb8858f36683c5e92a69b50261f43dd7e1597edf39843f39",
          "sha256": "dd64580b81ea07764dd1bf6f5e9d186c25c7cb3665f3f9484dc7d852c3990371",
          "sha1": "db89f388cf550e6f80388ca936b568d05b279fa4",
          "md5": "8503c6355f804ecc4eb69426b9ace284"
        }
      ]
    }
  ]
}
